api-version: 1.13
name: ServerChat
version: 1.8.1
author: Zao_hon
main: cn.blockmc.Zao_hon.ServerChat.ServerChat
softdepend: [Vault,PlayerPoint,PlaceholderAPI]
commands:
    ServerChat:
        aliases: [sc,sch]
Permissions:
    ServerChat.Admin:
        default: op
    ServerChat.Ignore:
        default: op
    ServerChat.Color:
        default: op
    ServerChat.Buy:
        default: All